# Generated by Django 4.1.2 on 2022-11-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sold',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
