# Generated by Django 4.1.2 on 2022-11-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_source',
            field=models.CharField(max_length=640),
        ),
    ]
