# Generated by Django 4.1.2 on 2022-11-12 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_image_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watching_users',
            field=models.ManyToManyField(related_name='watchers', to=settings.AUTH_USER_MODEL),
        ),
    ]
